#!/usr/bin/bash

#
# this script tests if container collection works as expected
#   It takes an optional single argument, the command to run for insights-client
#   if not specified it will default to redhat-access-insights
#
#   A reasonable alternative choice is "python ./redhat_access_insights/__init__.py"
#   which will run the version in the source directories
#
set -ex
    # -e fail the whole script if any command fails
    # -x show each command before it runs


cmd="$1"
if [ -z "$cmd" ]; then
    cmd=redhat-access-insights
fi

docker pull registry.access.redhat.com/rhel
docker pull docker.io/rhel
docker pull registry.access.redhat.com/rhel7.0

$cmd --verbose --register
$cmd --verbose --analyse-docker-image registry.access.redhat.com/rhel
$cmd --verbose --analyse-docker-image docker.io/rhel
$cmd --verbose --analyse-docker-image registry.access.redhat.com/rhel7.0
