.\" redhat-access-insights - Red Hat Access Insights
.TH "redhat-access-insights" "8" "" "Red Hat Access Insights" ""
.SH "NAME"
redhat\-access\-insights \- Red Hat Access Insights Client tool

.SH "SYNOPSIS"
.B redhat-access-insights [options]
.SH "DESCRIPTION"
\fBredhat\-access\-insights\fP is designed to help customers proactively resolve issues affecting business operations in Red Hat Enterprise Linux and Cloud Infrastructure environments. View alerts or learn more at https://access.redhat.com/insights/


.SH "OPTIONS"
.IP "-h, --help"
show this help message and exit
.IP "--version"
Display version
.IP "--register"
Register system to the Red Hat Access Insights Service
.IP "--unregister"
Unregister system from the Red Hat Access Insights Service
.IP "--update-collection-rules"
Refresh collection rules from Red Hat
Set Red Hat Access Insights to collect data once per week
.IP "--group=GROUP"
Group to add this system to during registration
.IP "--retry=RETRIES"
Number of times to retry uploading. 300 seconds between tries
.IP "--validate"
Validate remove.conf
.IP "--quiet"
Only display error messages to stdout
.IP "--silent"
Display no messages to stdout

.IP "--daily"
Set Red Hat Access Insights to collect data once per day
.IP "--weekly"

.SH "DEBUG OPTIONS"
.IP "--test-connection"
Test connectivity to Red Hat
.IP "--force-reregister"
Forcefully reregister this machine to Red Hat.  Use only as directed.
.IP "--verbose"
DEBUG output to stdout
.IP "--no-gpg"
Do not verify GPG signature
.IP "--no-upload"
Do not upload the archive
.IP "--no-tar-file"
Build the directory, but do not tar
.IP "--keep-archive"
Do not delete archive after upload

.SH "SEE ALSO"
.BR redhat-access-insights.conf (8)

.SH "AUTHOR"
Dan Varga <dvarga@redhat.com>\&
