.\" redhat-access-insights.conf - Red Hat Access Insights
.TH "redhat-access-insights.conf" "8" "" "Red Hat Access Insights Configuration" ""
.SH "NAME"
redhat\-access\-insights.conf \- Red Hat Access Insights Agent Configuration

.SH "DESCRIPTION"
The \fBredhat\-access\-insights.conf\fP file contains configuration information for \fBredhat\-access\-insights\fP, the agent for the Red Hat Access Insights service. This file is in an INI style format, option=value, default or example values are shown below.

[redhat-access-insights]\&
.IP "loglevel=DEBUG"
Change log level, valid options DEBUG, INFO, WARNING, ERROR, CRITICAL.
.IP "auto_config=False"
Automatically attempt to configure connectivity to Red Hat Access Insights
.IP "authmethod=BASIC"
Change authentication method, valid options BASIC, CERT. Default BASIC\&
.IP "upload_url=https://api.access.redhat.com/rs/telemetry"
URL to send uploads to
.IP "api_url=https://api.access.redhat.com/rs/telemetry/api"
URL to send API requests to
.IP "branch_info_url=https://api.access.redhat.com/rs/telemetry/api/v1/branch_info"
URL to obtain branch information from
.IP "remove_file=/etc/redhat-access-insights/remove.json"
File that can be used to prevent files or commands from being collected or to exclude lines containing a specified word.
This file MUST be in the following format, and MUST match exactly what is in the dynamic_config for file or command name
.br
{
  "commands": [
    {"command": "/sbin/lsmod",  "exclusion_pattern": ["usb"]},
    {"command": "/sbin/lspci"}
  ],
  "files": [
    {"file": "/etc/ssh/sshd_config", "exclusion_pattern": ["compression", "banner"]},
    {"file": "/etc/hosts"}, 
    {"file": "/var/log/redhat-access-insights/redhat-access-insights.log", "exclusion_pattern": []}
  ],
  "keywords": ["password", "giraffe", "moo"]
.br
}
.IP "fallback_file=/etc/redhat-access-insights/.fallback.json"
Path to .fallback, this is the dynamic config shipped with the RPM
.IP "dynamic_config_url=https://api.access.redhat.com/rs/telemetry/api/v1/static/uploader.json"
URL to retrieve dynamic configuration from.  GPG sig must me at this location + .asc
.IP "dynamic_config_file=/etc/redhat-access-insights/.cache.json"
Location of the dynamic configuration
.IP "auto_update=True"
Automatically update the dynamic configuration
.IP "cert_verify=/etc/redhat-access-insights/api.access.redhat.com.pem"
Location of the certificate chain for api.access.redhat.com used for Certificate Pinning\&
.IP "gpg=True"
Enable/Disable GPG verification of dynamic configuration
.IP "obfuscate=True"
Obfuscate ip addresses
.IP "obfuscate_hostname=True"
Obfuscate hostname
.IP "proxy=http://192.168.100.50:8080"
URL for the proxy
.IP "username="
Username to use when authmethod = BASIC
.IP "password="
Password to use when authmethod = BASIC

.SH "SEE ALSO"
.BR redhat-access-insights (8)

.SH "AUTHOR"
Dan Varga <dvarga@redhat.com>
