.\" redhat-access-insights - Red Hat Access Insights
.TH "redhat-access-insights" "8" "" "Red Hat Access Insights" ""
.SH "NAME"
redhat\-access\-insights \- Red Hat Access Insights Agent

.SH "SYNOPSIS"
.B redhat-access-insights [options]
.SH "DESCRIPTION"
\fBredhat\-access\-insights\fP can be used to analyze systems for potential issues. Issues and solutions can be seen at https://access.redhat.com/labs/insights or via product Web GUI frontends.  

.SH "OPTIONS"
.IP "--register"
Register system to Red Hat Access Insights Support
.IP "--update"
Get new rules from Red Hat
.IP "--validate"
Validate remove.json
.IP "--schedule"
Set Red Hat Access Insights's schedule only (no upload).
Must be used with --daily or --weekly
.IP "--daily"
Set Red Hat Access Insights to collect data once per day
.IP "--weekly"
Set Red Hat Access Insights to collect data once per week
.IP "--group=GROUP"
Group to add this system to during registration
.IP "--satellite-group"
Use this system's satellite group during registration
.IP "--test-connection"
Test connectivity to Red Hat
.IP "--verbose"
DEBUG output to stdout
.IP "--no-gpg"
Do not verify GPG signature
.IP "--regenerate"
Regenerate machine-id
.IP "--no-upload"
Do not upload the archive
.IP "--no-tar-file"
Build the directory, but do not tar
.IP "--keep-archive"
Do not delete archive after upload
.IP "--version"
Display version

.SH "SEE ALSO"
.BR redhat-access-insights.conf (8)

.SH "AUTHOR"
Dan Varga <dvarga@redhat.com>\&

